server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/knowledge_planet_node?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848
  application:
    name: graph-service