server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/knowledge_planet_user?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848
  application:
    name: user-service